# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build-publish-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./Projects/TutoProxy/TutoProxy.sln
    - name: Build
      run: dotnet build ./Projects/TutoProxy/TutoProxy.sln --no-restore 
    - name: Test
      run: dotnet test ./Projects/TutoProxy/TutoProxy.sln --no-build --verbosity normal       

    - name: Publish
      run: |
        dotnet publish ./Projects/TutoProxy/TutoProxy.Server/TutoProxy.Server.csproj -c PublishRelease --no-self-contained --use-current-runtime -o ./out/win/TutoProxy.Server --os win -p:PublishProfile=FolderProfile -p:DebugType=None -p:DebugSymbols=false
        dotnet publish ./Projects/TutoProxy/TutoProxy.Server/TutoProxy.Server.csproj -c PublishRelease --no-self-contained --use-current-runtime -o ./out/linux/TutoProxy.Server --os linux -p:PublishProfile=FolderProfile -p:DebugType=None 
        dotnet publish ./Projects/TutoProxy/TutoProxy.Client/TutoProxy.Client.csproj -c PublishRelease --no-self-contained --use-current-runtime -o ./out/win/TutoProxy.Client --os win -p:PublishProfile=FolderProfile -p:DebugType=None -p:DebugSymbols=false
        dotnet publish ./Projects/TutoProxy/TutoProxy.Client/TutoProxy.Client.csproj -c PublishRelease --no-self-contained --use-current-runtime -o ./out/linux/TutoProxy.Client --os linux -p:PublishProfile=FolderProfile -p:DebugType=None   

    - name: Deploy Win-Server
      uses: actions/upload-artifact@v4
      with:
        name: win-Server
        path: ./out/win/TutoProxy.Server/TutoProxy.Server.exe
        retention-days: 90

    - name: Deploy Win-Client
      uses: actions/upload-artifact@v4
      with:
        name: win-Client
        path: ./out/win/TutoProxy.Client/TutoProxy.Client.exe
        retention-days: 90   
        
    - name: Deploy Linux-Server
      uses: actions/upload-artifact@v4
      with:
        name: linux-Server
        path: ./out/linux/TutoProxy.Server/TutoProxy.Server
        retention-days: 90  
        
    - name: Deploy Linux-Client
      uses: actions/upload-artifact@v4
      with:
        name: linux-Client
        path: ./out/linux/TutoProxy.Client/TutoProxy.Client
        retention-days: 90    
